"""V2 : ajoute encore plus d'accents + a -> à contextuel."""
import re
import sys
sys.stdout.reconfigure(encoding='utf-8')

SRC = r"C:\Users\4067048\AppData\Local\Temp\alycante_lit\docgen\build_doc_v4.js"
DST = r"C:\Users\4067048\AppData\Local\Temp\alycante_lit\docgen\build_doc_v5.js"

# Mots a accentuer (ascii -> accentue)
REPL = {
    # Vague 1 - mots tres frequents
    'ete': 'été', 'etre': 'être', 'meme': 'même', 'memes': 'mêmes',
    'etait': 'était', 'etaient': 'étaient', 'tres': 'très', 'pres': 'près',
    'apres': 'après', 'malgre': 'malgré', 'aupres': 'auprès', 'deja': 'déjà',
    # E -> é mots courants
    'etude': 'étude', 'etudes': 'études',
    'evaluation': 'évaluation', 'evaluations': 'évaluations',
    'evalue': 'évalué', 'evaluer': 'évaluer', 'evaluee': 'évaluée',
    'evaluees': 'évaluées', 'evalues': 'évalués', 'evaluant': 'évaluant',
    'reponse': 'réponse', 'reponses': 'réponses',
    'repondu': 'répondu', 'repondre': 'répondre', 'repondent': 'répondent',
    'repondeurs': 'répondeurs',
    'recente': 'récente', 'recent': 'récent', 'recentes': 'récentes',
    'recents': 'récents', 'recemment': 'récemment',
    'recurrence': 'récurrence', 'recurrent': 'récurrent',
    'recurrents': 'récurrents', 'recurrente': 'récurrente',
    'recurrentes': 'récurrentes', 'recurrences': 'récurrences',
    'precoce': 'précoce', 'precoces': 'précoces',
    'precocement': 'précocement', 'precocite': 'précocité',
    'precis': 'précis', 'precise': 'précise', 'precises': 'précises',
    'precisement': 'précisément', 'precision': 'précision',
    'preciser': 'préciser',
    'detection': 'détection', 'detections': 'détections',
    'detecter': 'détecter', 'detecte': 'détecté',
    'detectee': 'détectée', 'detectees': 'détectées',
    'detectes': 'détectés', 'detectent': 'détectent',
    'detectable': 'détectable', 'detectables': 'détectables',
    'methode': 'méthode', 'methodes': 'méthodes',
    'methodologie': 'méthodologie', 'methodologique': 'méthodologique',
    'methodologiques': 'méthodologiques',
    'methodologiquement': 'méthodologiquement',
    'mediane': 'médiane', 'medianes': 'médianes',
    'medical': 'médical', 'medicale': 'médicale',
    'medicales': 'médicales', 'medicaux': 'médicaux',
    'general': 'général', 'generale': 'générale',
    'generales': 'générales', 'generaux': 'généraux',
    'generalement': 'généralement',
    'generalisable': 'généralisable', 'generalisabilite': 'généralisabilité',
    'generalisation': 'généralisation',
    'genome': 'génome', 'genomes': 'génomes',
    'genomique': 'génomique', 'genomiques': 'génomiques',
    'genotype': 'génotype', 'genotypes': 'génotypes',
    'genotypage': 'génotypage',
    'specifique': 'spécifique', 'specifiques': 'spécifiques',
    'specificite': 'spécificité', 'specifiquement': 'spécifiquement',
    'frequence': 'fréquence', 'frequences': 'fréquences',
    'frequent': 'fréquent', 'frequents': 'fréquents',
    'frequente': 'fréquente', 'frequentes': 'fréquentes',
    'frequemment': 'fréquemment',
    'eleve': 'élevé', 'elevee': 'élevée',
    'eleves': 'élevés', 'elevees': 'élevées',
    'differente': 'différente', 'differentes': 'différentes',
    'different': 'différent', 'differents': 'différents',
    'difference': 'différence', 'differences': 'différences',
    'differer': 'différer', 'differe': 'diffère',
    'developpe': 'développé', 'developpee': 'développée',
    'developpees': 'développées', 'developpes': 'développés',
    'developpement': 'développement', 'developpements': 'développements',
    'developper': 'développer', 'developperait': 'développerait',
    'developpent': 'développent',
    'considerable': 'considérable', 'considerables': 'considérables',
    'considerablement': 'considérablement',
    'considere': 'considère', 'considerent': 'considèrent',
    'considerees': 'considérées', 'consideres': 'considérés',
    'consideree': 'considérée',
    'cle': 'clé', 'cles': 'clés',
    'premiere': 'première', 'premieres': 'premières',
    'deuxieme': 'deuxième', 'deuxiemes': 'deuxièmes',
    'troisieme': 'troisième', 'troisiemes': 'troisièmes',
    'quatrieme': 'quatrième',
    'cinquieme': 'cinquième', 'sixieme': 'sixième',
    'septieme': 'septième', 'huitieme': 'huitième',
    'neuvieme': 'neuvième', 'dixieme': 'dixième',
    'derniere': 'dernière', 'dernieres': 'dernières',
    'particulierement': 'particulièrement',
    'particuliere': 'particulière', 'particulieres': 'particulières',
    'modele': 'modèle', 'modeles': 'modèles',
    'modelise': 'modélise', 'modelisee': 'modélisée',
    'modelisees': 'modélisées', 'modelises': 'modélisés',
    'modelisation': 'modélisation', 'modelisations': 'modélisations',
    'modeliser': 'modéliser',
    'probleme': 'problème', 'problemes': 'problèmes',
    'problematique': 'problématique',
    'systeme': 'système', 'systemes': 'systèmes',
    'systematique': 'systématique', 'systematiques': 'systématiques',
    'systematiquement': 'systématiquement',
    'theme': 'thème', 'themes': 'thèmes',
    'theorique': 'théorique', 'theoriques': 'théoriques',
    'therapeutique': 'thérapeutique', 'therapeutiques': 'thérapeutiques',
    'therapie': 'thérapie', 'therapies': 'thérapies',
    'caractere': 'caractère', 'caracteres': 'caractères',
    'caracterise': 'caractérise', 'caracterisee': 'caractérisée',
    'caracterisees': 'caractérisées', 'caracterises': 'caractérisés',
    'caracteristique': 'caractéristique', 'caracteristiques': 'caractéristiques',
    'caracterisation': 'caractérisation',
    'numero': 'numéro', 'numeros': 'numéros',
    'maniere': 'manière', 'manieres': 'manières',
    'critere': 'critère', 'criteres': 'critères',
    'qualite': 'qualité', 'qualites': 'qualités',
    'quantite': 'quantité', 'quantites': 'quantités',
    'difficulte': 'difficulté', 'difficultes': 'difficultés',
    'realite': 'réalité', 'realites': 'réalités',
    'realise': 'réalisé', 'realisee': 'réalisée',
    'realisees': 'réalisées', 'realises': 'réalisés',
    'realisation': 'réalisation', 'realiser': 'réaliser',
    'capacite': 'capacité', 'capacites': 'capacités',
    'cellularite': 'cellularité',
    'demonstration': 'démonstration',
    'demontre': 'démontré', 'demontrer': 'démontrer',
    'demontrent': 'démontrent', 'demontree': 'démontrée',
    'demontrees': 'démontrées', 'demontres': 'démontrés',
    'lesion': 'lésion', 'lesions': 'lésions',
    'amelioration': 'amélioration', 'ameliorations': 'améliorations',
    'ameliore': 'amélioré', 'amelioree': 'améliorée',
    'ameliorees': 'améliorées', 'ameliores': 'améliorés',
    'ameliorer': 'améliorer', 'ameliorent': 'améliorent',
    'pretraitement': 'prétraitement', 'pretraitements': 'prétraitements',
    'limitee': 'limitée', 'limitees': 'limitées',
    'maitrise': 'maîtrise', 'maitriser': 'maîtriser',
    'maitrisee': 'maîtrisée',
    'experience': 'expérience', 'experiences': 'expériences',
    'experimental': 'expérimental', 'experimentale': 'expérimentale',
    'experimentaux': 'expérimentaux', 'experimentee': 'expérimentée',
    'moleculaire': 'moléculaire', 'moleculaires': 'moléculaires',
    'echelle': 'échelle', 'echelles': 'échelles',
    'echec': 'échec', 'echecs': 'échecs',
    'eclairage': 'éclairage', 'ecriture': 'écriture',
    'enrole': 'enrôlé', 'enroles': 'enrôlés',
    'enrolee': 'enrôlée', 'enrolees': 'enrôlées',
    'enroler': 'enrôler',
    'role': 'rôle', 'roles': 'rôles',
    'controle': 'contrôle', 'controles': 'contrôles',
    'controlee': 'contrôlée', 'controler': 'contrôler',
    'periode': 'période', 'periodes': 'périodes',
    'percu': 'perçu',
    'apparait': 'apparaît', 'apparaitre': 'apparaître',
    'parait': 'paraît', 'paraitre': 'paraître',
    'connaitre': 'connaître',
    'phenotype': 'phénotype', 'phenotypes': 'phénotypes',
    'predicteur': 'prédicteur', 'predicteurs': 'prédicteurs',
    'predictive': 'prédictive', 'predictives': 'prédictives',
    'predictif': 'prédictif', 'predictifs': 'prédictifs',
    'prediction': 'prédiction', 'predictions': 'prédictions',
    'predire': 'prédire', 'predisaient': 'prédisaient',
    'predit': 'prédit', 'predite': 'prédite',
    'predits': 'prédits', 'predites': 'prédites',
    'represente': 'représenté', 'representee': 'représentée',
    'representees': 'représentées', 'representes': 'représentés',
    'representer': 'représenter', 'representent': 'représentent',
    'representation': 'représentation', 'representations': 'représentations',
    'representatif': 'représentatif', 'representatifs': 'représentatifs',
    'representative': 'représentative', 'representatives': 'représentatives',
    'representativite': 'représentativité',
    'prelevement': 'prélèvement', 'prelevements': 'prélèvements',
    'prelever': 'prélever', 'preleve': 'prélevé',
    'prelevee': 'prélevée', 'prelevees': 'prélevées',
    'preleves': 'prélevés',
    'agressif': 'agressif', 'agressifs': 'agressifs',
    'agressive': 'agressive', 'agressives': 'agressives',
    'agressivite': 'agressivité',
    'emerge': 'émerge', 'emerges': 'émergés',
    'emergee': 'émergée', 'emergees': 'émergées',
    'emergent': 'émergent', 'emergence': 'émergence',
    'emergences': 'émergences',
    'idee': 'idée', 'idees': 'idées',
    'enregistre': 'enregistré', 'enregistrement': 'enregistrement',
    'enregistree': 'enregistrée', 'enregistrees': 'enregistrées',
    'enregistres': 'enregistrés', 'enregistrer': 'enregistrer',
    'sensibilite': 'sensibilité', 'sensibilites': 'sensibilités',
    'priorite': 'priorité', 'priorites': 'priorités',
    'integre': 'intègre', 'integres': 'intégrés',
    'integree': 'intégrée', 'integrees': 'intégrées',
    'integration': 'intégration', 'integrer': 'intégrer',
    'integrent': 'intègrent',
    'inegalement': 'inégalement',
    'precedente': 'précédente', 'precedentes': 'précédentes',
    'precedent': 'précédent', 'precedents': 'précédents',
    'donnees': 'données', 'donnee': 'donnée',
    'donne': 'donné', 'donnes': 'donnés',
    'hypothese': 'hypothèse', 'hypotheses': 'hypothèses',
    'litterature': 'littérature',
    'rechute': 'rechute', 'rechutes': 'rechutes',
    'refractaire': 'réfractaire', 'refractaires': 'réfractaires',
    'refractarite': 'réfractarité',
    'severe': 'sévère', 'severes': 'sévères',
    'severement': 'sévèrement', 'severite': 'sévérité',
    'serie': 'série', 'series': 'séries',
    'analyses': 'analysés',  # ambigu mais souvent verbe
    'analysee': 'analysée', 'analysees': 'analysées',
    'definie': 'définie', 'definies': 'définies',
    'defini': 'défini', 'definis': 'définis',
    'definir': 'définir',
    'definition': 'définition', 'definitions': 'définitions',
    'efficacite': 'efficacité', 'efficacement': 'efficacement',
    'leucapherese': 'leucaphérèse',
    'cerebrale': 'cérébrale', 'cerebrales': 'cérébrales',
    'cerebral': 'cérébral', 'cerebraux': 'cérébraux',
    'encephalique': 'encéphalique', 'encephaliques': 'encéphaliques',
    'phasee': 'phasée', 'phasees': 'phasées',
    'autorisee': 'autorisée', 'autorisees': 'autorisées',
    'autorises': 'autorisés', 'autorise': 'autorisé',
    'autorisation': 'autorisation', 'autorisations': 'autorisations',
    'evolution': 'évolution', 'evolutions': 'évolutions',
    'evolutif': 'évolutif', 'evolutifs': 'évolutifs',
    'evolutive': 'évolutive', 'evolutives': 'évolutives',
    'evoluer': 'évoluer', 'evolue': 'évolué',
    'evoluee': 'évoluée', 'evolues': 'évolués',
    'evoluees': 'évoluées', 'evoluent': 'évoluent',
    'reduction': 'réduction', 'reductions': 'réductions',
    'reduire': 'réduire',
    'reduit': 'réduit', 'reduits': 'réduits',
    'reduite': 'réduite', 'reduites': 'réduites',
    'inferieur': 'inférieur', 'inferieure': 'inférieure',
    'inferieurs': 'inférieurs', 'inferieures': 'inférieures',
    'superieur': 'supérieur', 'superieure': 'supérieure',
    'superieurs': 'supérieurs', 'superieures': 'supérieures',
    'superiorite': 'supériorité',
    'reseau': 'réseau', 'reseaux': 'réseaux',
    'identite': 'identité',
    'identifie': 'identifié', 'identifiee': 'identifiée',
    'identifiees': 'identifiées', 'identifies': 'identifiés',
    'identification': 'identification',
    'gerable': 'gérable', 'gerables': 'gérables',
    'gerer': 'gérer', 'gere': 'géré',
    'geree': 'gérée', 'gerees': 'gérées',
    'geres': 'gérés',
    'metabolique': 'métabolique', 'metaboliques': 'métaboliques',
    'metabolisme': 'métabolisme',
    'meta': 'méta',
    'parametre': 'paramètre', 'parametres': 'paramètres',
    'parametrer': 'paramétrer', 'parametrique': 'paramétrique',
    'parametriques': 'paramétriques',
    'present': 'présent', 'presents': 'présents',
    'presente': 'présente', 'presentes': 'présentés',
    'presentation': 'présentation', 'presenter': 'présenter',
    'presentent': 'présentent', 'presentee': 'présentée',
    'presentees': 'présentées',
    'preserver': 'préserver',
    'preservatrice': 'préservatrice',
    'multivarie': 'multivarié', 'multivariee': 'multivariée',
    'multivariees': 'multivariées', 'multivaries': 'multivariés',
    'univarie': 'univarié', 'univariee': 'univariée',
    'univariees': 'univariées', 'univaries': 'univariés',
    'pathologie': 'pathologie', 'pathologies': 'pathologies',
    'pathologique': 'pathologique', 'pathologiques': 'pathologiques',
    'phenomene': 'phénomène', 'phenomenes': 'phénomènes',
    'cinetique': 'cinétique', 'cinetiques': 'cinétiques',
    'interpretation': 'interprétation', 'interpretations': 'interprétations',
    'interpreter': 'interpréter', 'interprete': 'interprété',
    'interpretee': 'interprétée', 'interpretees': 'interprétées',
    'interpretes': 'interprétés',
    'evidence': 'évidence', 'evidences': 'évidences',
    'evident': 'évident', 'evidents': 'évidents',
    'evidente': 'évidente', 'evidentes': 'évidentes',
    'evidemment': 'évidemment',
    'preferable': 'préférable', 'preferables': 'préférables',
    'preferentiellement': 'préférentiellement',
    'preference': 'préférence', 'preferences': 'préférences',
    'preferer': 'préférer',
    'experimente': 'expérimenté', 'experimentees': 'expérimentées',
    'experimentes': 'expérimentés', 'experimentee': 'expérimentée',
    'pediatrique': 'pédiatrique', 'pediatriques': 'pédiatriques',
    'arret': 'arrêt', 'arrets': 'arrêts',
    'arreter': 'arrêter', 'arrete': 'arrêté',
    'enquete': 'enquête', 'enquetes': 'enquêtes',
    'verifie': 'vérifié', 'verifier': 'vérifier',
    'verifiee': 'vérifiée', 'verifiees': 'vérifiées',
    'verifies': 'vérifiés',
    'verification': 'vérification', 'verifications': 'vérifications',
    'realisable': 'réalisable', 'realisables': 'réalisables',
    'inconvenient': 'inconvénient', 'inconvenients': 'inconvénients',
    'evenement': 'événement', 'evenements': 'événements',
    'individualise': 'individualisé', 'individualisee': 'individualisée',
    'individualisees': 'individualisées', 'individualises': 'individualisés',
    'integratif': 'intégratif', 'integratifs': 'intégratifs',
    'integrative': 'intégrative', 'integratives': 'intégratives',
    'pionnier': 'pionnier', 'pionniere': 'pionnière',
    'pionnieres': 'pionnières',
    'maturite': 'maturité',
    'lucidite': 'lucidité',
    'dependance': 'dépendance', 'dependances': 'dépendances',
    'dependant': 'dépendant', 'dependants': 'dépendants',
    'dependante': 'dépendante', 'dependantes': 'dépendantes',
    'dependent': 'dépendent', 'depend': 'dépend',
    'dependra': 'dépendra',
    'fragilite': 'fragilité', 'fragilites': 'fragilités',
    'numerique': 'numérique', 'numeriques': 'numériques',
    'numeriquement': 'numériquement',
    'echantillon': 'échantillon', 'echantillons': 'échantillons',
    'echantillonnage': 'échantillonnage',
    'temperent': 'tempèrent', 'temperer': 'tempérer',
    'temperees': 'tempérées', 'tempere': 'tempéré',
    # Mots additionnels apres analyse v5
    'bispecifique': 'bispécifique', 'bispecifiques': 'bispécifiques',
    'traites': 'traités', 'traitees': 'traitées',
    'residuel': 'résiduel', 'residuelle': 'résiduelle',
    'residuels': 'résiduels', 'residuelles': 'résiduelles',
    'eligible': 'éligible', 'eligibles': 'éligibles',
    'ineligible': 'inéligible', 'ineligibles': 'inéligibles',
    'experimentale': 'expérimentale', 'experimentales': 'expérimentales',
    'pulmonaire': 'pulmonaire',  # pas d'accent
    'celebre': 'célèbre', 'celebres': 'célèbres',
    'commune': 'commune', 'communes': 'communes', 'commun': 'commun',
    'communs': 'communs',  # pas d'accent
    'recurrent': 'récurrent', 'recurrents': 'récurrents',
    'principale': 'principale', 'principales': 'principales',
    'principal': 'principal', 'principaux': 'principaux',
    'definitive': 'définitive', 'definitives': 'définitives',
    'definitif': 'définitif', 'definitifs': 'définitifs',
    'extreme': 'extrême', 'extremes': 'extrêmes',
    'extremement': 'extrêmement',
    'declinaison': 'déclinaison', 'declinaisons': 'déclinaisons',
    'decline': 'décline', 'declinent': 'déclinent',
    'declines': 'déclinés', 'declinee': 'déclinée',
    'declinees': 'déclinées',
    'concret': 'concret', 'concrete': 'concrète',
    'concretement': 'concrètement', 'concrets': 'concrets',
    'concretes': 'concrètes',
    'aiguille': 'aiguille', 'aiguilles': 'aiguilles',
    'incertitude': 'incertitude', 'incertitudes': 'incertitudes',
    'incertain': 'incertain', 'incertains': 'incertains',
    'incertaine': 'incertaine', 'incertaines': 'incertaines',
    'considerablement': 'considérablement',
    'considerable': 'considérable',
    'considerables': 'considérables',
    # Autres
    'evalue': 'évalué', 'evaluee': 'évaluée',
    'objectif': 'objectif', 'objectifs': 'objectifs',
    'aboutie': 'aboutie',  # pas d'accent en realite
    'rarement': 'rarement',  # pas d'accent
    'extension': 'extension',  # pas d'accent
    'pretraitee': 'prétraitée', 'pretraitees': 'prétraitées',
    'pretraitement': 'prétraitement',
    'efficacite': 'efficacité', 'inefficacite': 'inefficacité',
    'cumule': 'cumulé', 'cumulee': 'cumulée',
    'cumulees': 'cumulées', 'cumules': 'cumulés',
    'limite': 'limite',  # ambigu
    'completee': 'complétée', 'completer': 'compléter',
    'complete': 'complète',  # ambigu adj/verbe
    'completes': 'complètes',
    'complement': 'complément', 'complements': 'compléments',
    'complementaire': 'complémentaire', 'complementaires': 'complémentaires',
    'complementarite': 'complémentarité',
    'profondeur': 'profondeur',  # pas d'accent
    'profond': 'profond', 'profonde': 'profonde',
    'profondes': 'profondes', 'profonds': 'profonds',
    'profondement': 'profondément',
    'parametre': 'paramètre',
    'pretres': 'prêtres',
    'pretees': 'prêtées',
    'profession': 'profession',  # pas d'accent
    'professionnel': 'professionnel',  # pas d'accent
    'reglementaire': 'réglementaire',
    'reglementaires': 'réglementaires',
    'reglementation': 'réglementation',
    'inserm': 'Inserm',  # pas pertinent ici
    'reflete': 'reflète', 'refletes': 'reflètes',
    'refletees': 'reflétées',
    'reflechi': 'réfléchi', 'reflechie': 'réfléchie',
    'realise': 'réalisé',
    'a-cote': 'à-côté',
    # NOTE: "references" est exclu car casse les noms de fichiers JS
}


def apply_replacements(text):
    sorted_keys = sorted(REPL.keys(), key=len, reverse=True)
    for ascii_word in sorted_keys:
        accented = REPL[ascii_word]
        if ascii_word == accented:
            continue
        pattern = r'\b' + re.escape(ascii_word) + r'\b'
        text = re.sub(pattern, accented, text)
    return text


def apply_a_to_a(text):
    """Remplacement contextuel de 'a' (verbe avoir) vs 'à' (preposition)."""
    # Patterns specifiques ou 'a' est presque toujours 'à'
    patterns = [
        # a + nombre
        (r"\ba (?=\d)", "à "),
        # a + mois/an/jour
        (r"\ba (?=mois\b|an\b|ans\b|jours?\b|semaines?\b|cycles?\b|fois\b)", "à "),
        # a + article
        (r"\ba (?=la\b|le\b|les\b|un\b|une\b|des\b|ce\b|ces\b|cet\b|cette\b)", "à "),
        # a + adjectif possessif
        (r"\ba (?=notre\b|votre\b|leur\b|leurs\b|nos\b|vos\b|son\b|sa\b|ses\b|mon\b|ma\b|mes\b|ton\b|ta\b|tes\b)", "à "),
        # a + tout/tous/chaque
        (r"\ba (?=tout\b|toute\b|tous\b|toutes\b|chaque\b|chacun\b|chacune\b)", "à "),
        # a + autre/autres
        (r"\ba (?=autre\b|autres\b|d'autres\b|d autres\b)", "à "),
        # locutions
        (r"\ba propos\b", "à propos"),
        (r"\ba savoir\b", "à savoir"),
        (r"\ba partir\b", "à partir"),
        (r"\ba peine\b", "à peine"),
        (r"\ba moins\b", "à moins"),
        (r"\ba travers\b", "à travers"),
        (r"\ba cause\b", "à cause"),
        (r"\ba mesure\b", "à mesure"),
        (r"\ba l\b", "à l"),
        (r"\ba l'", "à l'"),
        (r"\bjusqu a\b", "jusqu’à"),
        (r"\bvis-a-vis\b", "vis-à-vis"),
        (r"\bvis a vis\b", "vis-à-vis"),
        (r"\bface a\b", "face à"),
        (r"\bgrace a\b", "grâce à"),
        (r"\bquant a\b", "quant à"),
        (r"\bnotre\b a", "notre"),  # not needed
        (r"\bpar rapport a\b", "par rapport à"),
        # a + verbe infinitif courant
        (r"\ba etre\b", "à être"),
        (r"\ba faire\b", "à faire"),
        (r"\ba venir\b", "à venir"),
        (r"\ba dire\b", "à dire"),
        (r"\ba voir\b", "à voir"),
        (r"\ba prendre\b", "à prendre"),
        (r"\ba refaire\b", "à refaire"),
        (r"\ba realiser\b", "à réaliser"),
        (r"\ba accomplir\b", "à accomplir"),
        (r"\ba ce que\b", "à ce que"),
        (r"\ba ce sujet\b", "à ce sujet"),
        # ALYCANTE specifique
        (r"\ba ALYCANTE\b", "à ALYCANTE"),
        (r"\ba l'etude\b", "à l'étude"),
        (r"\ba l'aune\b", "à l'aune"),
        (r"\ba la lumiere\b", "à la lumière"),
    ]
    for pat, rep in patterns:
        text = re.sub(pat, rep, text)
    return text


with open(SRC, 'r', encoding='utf-8') as f:
    text = f.read()

original = text
text = apply_replacements(text)
text = apply_a_to_a(text)

# Compte differences
n_diff = sum(1 for a, b in zip(original, text) if a != b)
print(f"Caracteres modifies (approx): {n_diff}")

with open(DST, 'w', encoding='utf-8') as f:
    f.write(text)
print(f"Ecrit: {DST}")
