"""V3 : ajoute encore plus d'accents + apostrophes typographiques."""
import re
import sys
sys.stdout.reconfigure(encoding='utf-8')

SRC = r"C:\Users\4067048\AppData\Local\Temp\alycante_lit\docgen\build_doc_v5.js"
DST = r"C:\Users\4067048\AppData\Local\Temp\alycante_lit\docgen\build_doc_v5b.js"

# Mots additionnels apres analyse v5
REPL = {
    # Verbes/participes avec accent
    'demontre': 'démontré',
    'demontrant': 'démontrant',
    'demontree': 'démontrée',
    'demontrees': 'démontrées',
    'demontrer': 'démontrer',
    'demontres': 'démontrés',
    'demontrent': 'démontrent',
    'demonstration': 'démonstration',
    'poolee': 'poolée', 'poolees': 'poolées',
    'pooles': 'poolés', 'pooler': 'pooler',
    'releve': 'relève', 'releves': 'relevés',
    'relever': 'relever',
    'reveler': 'révéler',
    'revelees': 'révélées',
    'reveles': 'révélés',
    'revele': 'révélé', 'revelee': 'révélée',
    'revelation': 'révélation', 'revelations': 'révélations',
    'esperer': 'espérer', 'espere': 'espère',
    'esperance': 'espérance',
    'reflete': 'reflète', 'refletes': 'reflètes',
    'refletes': 'reflétés', 'refletees': 'reflétées',
    'refletant': 'reflétant', 'refleter': 'refléter',
    'reflechi': 'réfléchi', 'reflechie': 'réfléchie',
    'reflechir': 'réfléchir', 'reflechissent': 'réfléchissent',
    'lisocabtagene': 'lisocabtagène',  # parfois accentue
    'axicabtagene': 'axicabtagène',
    'tisagenlecleucel': 'tisagenlecleucel',  # marque, pas d'accent
    'lithique': 'lithique',  # pas d'accent
    'parametre': 'paramètre',
    'parametres': 'paramètres',
    'rigidite': 'rigidité',
    'serieuse': 'sérieuse',
    'serieuses': 'sérieuses',
    'reglee': 'réglée',
    'reglees': 'réglées', 'regle': 'réglé', 'regles': 'réglés',
    'regler': 'régler',
    'demonstration': 'démonstration',
    'apres': 'après',
    'remplacement': 'remplacement',
    'remplacements': 'remplacements',
    'consideree': 'considérée',
    'consideres': 'considérés',
    'considerees': 'considérées',
    'cliniquement': 'cliniquement',
    'biologique': 'biologique',
    'avec': 'avec',
    'precis': 'précis',
    'precise': 'précise',
    'precises': 'précises',
    'precisement': 'précisément',
    'inegalement': 'inégalement',
    'aire': 'aire',  # pas d'accent
    'critere': 'critère',
    'criteres': 'critères',
    'recouvrement': 'recouvrement',  # pas d'accent
    'beneficier': 'bénéficier', 'beneficie': 'bénéficie',
    'beneficient': 'bénéficient', 'beneficies': 'bénéficiés',
    'beneficier': 'bénéficier', 'benefice': 'bénéfice',
    'benefices': 'bénéfices',
    'bilan': 'bilan',  # pas d'accent
    'preuve': 'preuve',  # pas d'accent
    'preuves': 'preuves',
    'desormais': 'désormais',
    'tachent': 'tâchent', 'tachons': 'tâchons',
    'tachant': 'tâchant',  # rare
    'chimioimmunotherapie': 'chimio-immunothérapie',
    'chimiotherapie': 'chimiothérapie',
    'chimiotherapies': 'chimiothérapies',
    'multicentre': 'multicentre',  # pas d'accent
    'epoque': 'époque',
    'inegale': 'inégale', 'inegales': 'inégales',
    'inegal': 'inégal', 'inegaux': 'inégaux',
    'rigueur': 'rigueur',
    'rigoureux': 'rigoureux',
    'rigoureuse': 'rigoureuse',
    'inverse': 'inverse',  # pas d'accent
    'transversal': 'transversal',  # pas d'accent
    'tete': 'tête',
    'evidence': 'évidence',
    'reservoir': 'réservoir',
    'reserve': 'réserve', 'reserves': 'réserves',
    'reservee': 'réservée',
    'reservees': 'réservées',
    'reserves': 'réservés',
    'reserver': 'réserver',
    'reservation': 'réservation',
    'maintien': 'maintien',  # pas d'accent
    'maintenir': 'maintenir',
    'maintenu': 'maintenu',
    'maintenue': 'maintenue',
    'maintenus': 'maintenus',
    'maintenues': 'maintenues',
    'maintenant': 'maintenant',
    'cidessus': 'ci-dessus',
    'ci-dessus': 'ci-dessus',
    'ci-apres': 'ci-après',
    'cidessous': 'ci-dessous',
    'ci-dessous': 'ci-dessous',
    'objective': 'objective',  # pas d'accent
    'objectivement': 'objectivement',
    'objectiver': 'objectiver',
    'objective': 'objectivée',  # selon contexte
    'objectivees': 'objectivées',
    'inclusivement': 'inclusivement',
    'inclusion': 'inclusion',  # pas d'accent
    'inclus': 'inclus',  # pas d'accent
    'incluse': 'incluse',
    'incluses': 'incluses',
    'incluant': 'incluant',
    'inclure': 'inclure',
    'reprise': 'reprise',  # pas d'accent
    'reprises': 'reprises',
    'reprend': 'reprend',  # pas d'accent
    'reprendre': 'reprendre',
    'remise': 'remise',  # pas d'accent
    'remises': 'remises',
    'remis': 'remis',
    'remettant': 'remettant',
    'remettre': 'remettre',
    'rejet': 'rejet',  # pas d'accent
    'rejets': 'rejets',
    'rejeter': 'rejeter',
    'rejetee': 'rejetée',
    'rejetees': 'rejetées',
    'rejetes': 'rejetés',
    'rejete': 'rejeté',
    'rejette': 'rejette',
    'rejettent': 'rejettent',
    'fragilite': 'fragilité',
    'tete-de-pont': 'tête-de-pont',
    'tete': 'tête',
    'a-cote': 'à-côté',
    # Mots un peu plus rares
    'compreense': 'compréhension',  # typo
    'comprehension': 'compréhension',
    'compreensible': 'compréhensible',
    'comprehensible': 'compréhensible',
    'comprehensibles': 'compréhensibles',
    'compreensives': 'compréhensives',
    'comprehensive': 'compréhensive',
    'profondement': 'profondément',
    'profondemment': 'profondément',  # typo
    'redaction': 'rédaction',
    'redactions': 'rédactions',
    'redacteur': 'rédacteur',
    'redacteurs': 'rédacteurs',
    'redactrice': 'rédactrice',
    'redaction': 'rédaction',
    'redige': 'rédigé',
    'redigee': 'rédigée',
    'redigees': 'rédigées',
    'rediges': 'rédigés',
    'rediger': 'rédiger',
    'redigeur': 'rédacteur',  # erreur
    'rapporter': 'rapporter',  # pas d'accent
    'rapporte': 'rapporté',
    'rapportes': 'rapportés',
    'rapportees': 'rapportées',
    'rapportee': 'rapportée',
    'rapporteront': 'rapporteront',
    'rapportaient': 'rapportaient',
    'rapportant': 'rapportant',
    'reagir': 'réagir',
    'reagit': 'réagit',
    'reagissent': 'réagissent',
    'reaction': 'réaction',
    'reactions': 'réactions',
    'reactif': 'réactif',
    'reactifs': 'réactifs',
    'reactive': 'réactive',
    'reactives': 'réactives',
    'reactivation': 'réactivation',
    'reactivations': 'réactivations',
    'reanalysis': 'réanalysis',  # english
    'reanimation': 'réanimation',
    'reentry': 'reentry',  # english
    'reorganisation': 'réorganisation',
    'reorganisations': 'réorganisations',
    'reorganise': 'réorganisé',
    'reorganisee': 'réorganisée',
    'reorganises': 'réorganisés',
    'reorganiser': 'réorganiser',
    'reorganisent': 'réorganisent',
    'reduction': 'réduction',
    'reducteur': 'réducteur',
    'reducteurs': 'réducteurs',
    'reductrice': 'réductrice',
    'reductrices': 'réductrices',
    'redondance': 'redondance',  # pas d'accent
    'redondances': 'redondances',
    'redondant': 'redondant',
    'redondants': 'redondants',
    'redondante': 'redondante',
    'redondantes': 'redondantes',
    'reine': 'reine',
    'realisme': 'réalisme',
    'realiste': 'réaliste',
    'realistes': 'réalistes',
    'realiste': 'réaliste',
    'realistic': 'réaliste',  # english
    'preliminary': 'préliminary',  # english
    'preliminaire': 'préliminaire',
    'preliminaires': 'préliminaires',
    'preuve': 'preuve',
    'irrelevant': 'irrelevant',
    'irreversibilite': 'irréversibilité',
    'irreversible': 'irréversible',
    'irreversibles': 'irréversibles',
    'derniere': 'dernière',
    'dernieres': 'dernières',
    'dernier': 'dernier',
    'derniers': 'derniers',
    'numero': 'numéro',
    'numeros': 'numéros',
    'maitre': 'maître',
    'maitres': 'maîtres',
    'maitresse': 'maîtresse',
    'maitresses': 'maîtresses',
    'pretes': 'prêtes', 'prets': 'prêts',
    'prete': 'prête', 'pret': 'prêt',
    'preter': 'prêter',
    'pretait': 'prêtait',
    'pretent': 'prêtent',
    'preteur': 'prêteur',
    'preteurs': 'prêteurs',
    'preteuse': 'prêteuse',
    'preteuses': 'prêteuses',
    'precoces': 'précoces',
    'precocement': 'précocement',
    'modifie': 'modifié', 'modifiee': 'modifiée',
    'modifiees': 'modifiées', 'modifies': 'modifiés',
    'modifier': 'modifier',
    'modification': 'modification',
    'modifications': 'modifications',
    'transcription': 'transcription',  # pas d'accent
    'transcriptions': 'transcriptions',
    'transmettre': 'transmettre',
    'transmis': 'transmis',
    'transmise': 'transmise',
    'transmises': 'transmises',
    'transmission': 'transmission',
    'transmissions': 'transmissions',
}


def apply_replacements(text):
    sorted_keys = sorted(REPL.keys(), key=len, reverse=True)
    for ascii_word in sorted_keys:
        accented = REPL[ascii_word]
        if ascii_word == accented:
            continue
        pattern = r'\b' + re.escape(ascii_word) + r'\b'
        text = re.sub(pattern, accented, text)
    return text


def apply_apostrophes(text):
    """Insere apostrophes typographiques pour 'd une', 'l a', etc.
    Utilise l'apostrophe Unicode ’ (') pour ne pas casser le JS."""
    APO = '’'  # '
    patterns = [
        # 'd une', 'd un' -> "d'une", "d'un"
        (r"\bd un\b", f"d{APO}un"),
        (r"\bd une\b", f"d{APO}une"),
        (r"\bd autre\b", f"d{APO}autre"),
        (r"\bd autres\b", f"d{APO}autres"),
        (r"\bd ailleurs\b", f"d{APO}ailleurs"),
        (r"\bd abord\b", f"d{APO}abord"),
        (r"\bd accord\b", f"d{APO}accord"),
        (r"\bd ajustement\b", f"d{APO}ajustement"),
        (r"\bd application\b", f"d{APO}application"),
        (r"\bd applications\b", f"d{APO}applications"),
        (r"\bd appui\b", f"d{APO}appui"),
        (r"\bd argument\b", f"d{APO}argument"),
        (r"\bd arguments\b", f"d{APO}arguments"),
        (r"\bd autres\b", f"d{APO}autres"),
        (r"\bd avoir\b", f"d{APO}avoir"),
        (r"\bd echec\b", f"d{APO}échec"),
        (r"\bd echantillon\b", f"d{APO}échantillon"),
        (r"\bd ecart\b", f"d{APO}écart"),
        (r"\bd effet\b", f"d{APO}effet"),
        (r"\bd effets\b", f"d{APO}effets"),
        (r"\bd elevation\b", f"d{APO}élévation"),
        (r"\bd emergence\b", f"d{APO}émergence"),
        (r"\bd entre\b", f"d{APO}entre"),
        (r"\bd entree\b", f"d{APO}entrée"),
        (r"\bd erreur\b", f"d{APO}erreur"),
        (r"\bd erreurs\b", f"d{APO}erreurs"),
        (r"\bd essai\b", f"d{APO}essai"),
        (r"\bd essais\b", f"d{APO}essais"),
        (r"\bd etude\b", f"d{APO}étude"),
        (r"\bd études\b", f"d{APO}études"),
        (r"\bd evaluer\b", f"d{APO}évaluer"),
        (r"\bd evaluation\b", f"d{APO}évaluation"),
        (r"\bd evenement\b", f"d{APO}événement"),
        (r"\bd événement\b", f"d{APO}événement"),
        (r"\bd evolution\b", f"d{APO}évolution"),
        (r"\bd hypoth\b", f"d{APO}hypoth"),
        (r"\bd identifier\b", f"d{APO}identifier"),
        (r"\bd implication\b", f"d{APO}implication"),
        (r"\bd implementation\b", f"d{APO}implémentation"),
        (r"\bd inclusion\b", f"d{APO}inclusion"),
        (r"\bd indication\b", f"d{APO}indication"),
        (r"\bd information\b", f"d{APO}information"),
        (r"\bd intervention\b", f"d{APO}intervention"),
        (r"\bd integration\b", f"d{APO}intégration"),
        (r"\bd organes\b", f"d{APO}organes"),
        (r"\bd ordre\b", f"d{APO}ordre"),
        (r"\bd origine\b", f"d{APO}origine"),
        (r"\bd un seul\b", f"d{APO}un seul"),
        (r"\bd une\b", f"d{APO}une"),
        (r"\bd entre\b", f"d{APO}entre"),
        # 'l a', 'l etude', etc.
        (r"\bl etude\b", f"l{APO}étude"),
        (r"\bl essai\b", f"l{APO}essai"),
        (r"\bl analyse\b", f"l{APO}analyse"),
        (r"\bl analyste\b", f"l{APO}analyste"),
        (r"\bl autre\b", f"l{APO}autre"),
        (r"\bl autres\b", f"l{APO}autres"),
        (r"\bl objectif\b", f"l{APO}objectif"),
        (r"\bl efficacite\b", f"l{APO}efficacité"),
        (r"\bl efficacité\b", f"l{APO}efficacité"),
        (r"\bl avantage\b", f"l{APO}avantage"),
        (r"\bl ensemble\b", f"l{APO}ensemble"),
        (r"\bl emergence\b", f"l{APO}émergence"),
        (r"\bl identification\b", f"l{APO}identification"),
        (r"\bl integration\b", f"l{APO}intégration"),
        (r"\bl integration\b", f"l{APO}intégration"),
        (r"\bl etat\b", f"l{APO}état"),
        (r"\bl interpretation\b", f"l{APO}interprétation"),
        (r"\bl interprétation\b", f"l{APO}interprétation"),
        (r"\bl impact\b", f"l{APO}impact"),
        (r"\bl imagerie\b", f"l{APO}imagerie"),
        (r"\bl approche\b", f"l{APO}approche"),
        (r"\bl application\b", f"l{APO}application"),
        (r"\bl approbation\b", f"l{APO}approbation"),
        (r"\bl absence\b", f"l{APO}absence"),
        (r"\bl axi-cel\b", f"l{APO}axi-cel"),
        (r"\bl etude\b", f"l{APO}étude"),
        (r"\bl etat\b", f"l{APO}état"),
        (r"\bl etranger\b", f"l{APO}étranger"),
        (r"\bl heterogeneite\b", f"l{APO}hétérogénéité"),
        (r"\bl hétérogénéité\b", f"l{APO}hétérogénéité"),
        (r"\bl histoire\b", f"l{APO}histoire"),
        (r"\bl hopital\b", f"l{APO}hôpital"),
        (r"\bl hospitalisation\b", f"l{APO}hospitalisation"),
        (r"\bl hypothese\b", f"l{APO}hypothèse"),
        (r"\bl idee\b", f"l{APO}idée"),
        (r"\bl idée\b", f"l{APO}idée"),
        (r"\bl identification\b", f"l{APO}identification"),
        (r"\bl illustration\b", f"l{APO}illustration"),
        (r"\bl immunoglobuline\b", f"l{APO}immunoglobuline"),
        (r"\bl imposition\b", f"l{APO}imposition"),
        (r"\bl impossibilite\b", f"l{APO}impossibilité"),
        (r"\bl impossibilité\b", f"l{APO}impossibilité"),
        (r"\bl impulsion\b", f"l{APO}impulsion"),
        (r"\bl incidence\b", f"l{APO}incidence"),
        (r"\bl independence\b", f"l{APO}indépendance"),
        (r"\bl indépendance\b", f"l{APO}indépendance"),
        (r"\bl inflammation\b", f"l{APO}inflammation"),
        (r"\bl initialisation\b", f"l{APO}initialisation"),
        (r"\bl institution\b", f"l{APO}institution"),
        (r"\bl integration\b", f"l{APO}intégration"),
        (r"\bl intervention\b", f"l{APO}intervention"),
        (r"\bl introduction\b", f"l{APO}introduction"),
        (r"\bl issue\b", f"l{APO}issue"),
        (r"\bl objectif\b", f"l{APO}objectif"),
        (r"\bl observation\b", f"l{APO}observation"),
        (r"\bl ordre\b", f"l{APO}ordre"),
        (r"\bl original\b", f"l{APO}original"),
        (r"\bl originalite\b", f"l{APO}originalité"),
        (r"\bl originalité\b", f"l{APO}originalité"),
        (r"\bl origine\b", f"l{APO}origine"),
        (r"\bl outil\b", f"l{APO}outil"),
        # 'n est', 'n a', etc.
        (r"\bn est\b", f"n{APO}est"),
        (r"\bn a pas\b", f"n{APO}a pas"),
        (r"\bn ont\b", f"n{APO}ont"),
        (r"\bn etait\b", f"n{APO}était"),
        (r"\bn etaient\b", f"n{APO}étaient"),
        (r"\bn a\b", f"n{APO}a"),
        # 's etend', 's accompagne', etc.
        (r"\bs accompagne\b", f"s{APO}accompagne"),
        (r"\bs accompagnent\b", f"s{APO}accompagnent"),
        (r"\bs accompagnant\b", f"s{APO}accompagnant"),
        (r"\bs accroit\b", f"s{APO}accroît"),
        (r"\bs ajoute\b", f"s{APO}ajoute"),
        (r"\bs ajustent\b", f"s{APO}ajustent"),
        (r"\bs applique\b", f"s{APO}applique"),
        (r"\bs appliquent\b", f"s{APO}appliquent"),
        (r"\bs appuie\b", f"s{APO}appuie"),
        (r"\bs appuient\b", f"s{APO}appuient"),
        (r"\bs avere\b", f"s{APO}avère"),
        (r"\bs avèrent\b", f"s{APO}avèrent"),
        (r"\bs en suit\b", f"s{APO}en suit"),
        (r"\bs etend\b", f"s{APO}étend"),
        (r"\bs etend\b", f"s{APO}étend"),
        (r"\bs etendent\b", f"s{APO}étendent"),
        (r"\bs imposer\b", f"s{APO}imposer"),
        (r"\bs imposent\b", f"s{APO}imposent"),
        (r"\bs inscrit\b", f"s{APO}inscrit"),
        (r"\bs inscrivent\b", f"s{APO}inscrivent"),
        (r"\bs ouvrent\b", f"s{APO}ouvrent"),
        (r"\bs ouvre\b", f"s{APO}ouvre"),
        # 'c est', 'c etait'
        (r"\bc est\b", f"c{APO}est"),
        (r"\bc etait\b", f"c{APO}était"),
        (r"\bc etaient\b", f"c{APO}étaient"),
        # 'jusqu a'
        (r"\bjusqu a\b", f"jusqu{APO}à"),
        (r"\bjusqu à\b", f"jusqu{APO}à"),
        # 'aujourd hui'
        (r"\baujourd hui\b", f"aujourd{APO}hui"),
        # 'qu'
        (r"\bqu il\b", f"qu{APO}il"),
        (r"\bqu ils\b", f"qu{APO}ils"),
        (r"\bqu elle\b", f"qu{APO}elle"),
        (r"\bqu elles\b", f"qu{APO}elles"),
        (r"\bqu on\b", f"qu{APO}on"),
        (r"\bqu un\b", f"qu{APO}un"),
        (r"\bqu une\b", f"qu{APO}une"),
        (r"\bqu en\b", f"qu{APO}en"),
        (r"\bqu a\b", f"qu{APO}à"),
        (r"\bqu apres\b", f"qu{APO}après"),
        (r"\bqu après\b", f"qu{APO}après"),
        (r"\bqu avec\b", f"qu{APO}avec"),
        (r"\bqu aucune\b", f"qu{APO}aucune"),
        (r"\bqu aucun\b", f"qu{APO}aucun"),
        (r"\bqu eux\b", f"qu{APO}eux"),
        (r"\bqu ici\b", f"qu{APO}ici"),
        (r"\bqu hier\b", f"qu{APO}hier"),
        # m' t'
        (r"\bm a\b", f"m{APO}a"),
        (r"\bm en\b", f"m{APO}en"),
        (r"\bt a\b", f"t{APO}a"),
        # j'
        (r"\bj ai\b", f"j{APO}ai"),
        (r"\bj avais\b", f"j{APO}avais"),
    ]
    for pat, rep in patterns:
        text = re.sub(pat, rep, text)
    return text


with open(SRC, 'r', encoding='utf-8') as f:
    text = f.read()

original = text
text = apply_replacements(text)
text = apply_apostrophes(text)

n_diff = sum(1 for a, b in zip(original, text) if a != b)
print(f"Caracteres modifies: {n_diff}")

with open(DST, 'w', encoding='utf-8') as f:
    f.write(text)
print(f"Ecrit: {DST}")
